/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.utils.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Ticket Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch (IOException e){
            System.out.println("There is something wrong");
            return;
        }

        Train trainSelectedForBooking = null;
        String source = null;
        String dest = null;
        User userToLogIn = null;

        while(option != 7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = sc.nextInt();

            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = sc.next();
                    User user = new User(nameToSignUp, UUID.randomUUID().toString(), passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>());
                    userBookingService.signUp(user);
                    break;

                case 2:
                    System.out.println("Enter the username: ");
                    String nameToLogIn = sc.next();

                    System.out.println("Enter the password");
                    String passwordToLogIn = sc.next();

                    userToLogIn = new User(nameToLogIn, UUID.randomUUID().toString(), passwordToLogIn, UserServiceUtil.hashPassword(passwordToLogIn), new ArrayList<>());

                    try {
                        userBookingService = new UserBookingService(userToLogIn);

                        if(userBookingService.loginUser()){
                            System.out.println("Login successful");
                        }else{
                            System.out.println("Invalid username or password");
                        }
                    }catch (IOException ex){
                        System.out.println("Something went wrong while logging in.");
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Enter your source station");
                    source = sc.next();
                    System.out.println("Enter your destination station");
                    dest = sc.next();
                    List<Train> trains = userBookingService.getTrains(source, dest);
                    int index = 1;
                    for(Train t: trains){
                        System.out.println(index + " Train id : " + t.getTrainId());
                        for(Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
                            System.out.println("Station " + entry.getKey() + " time: " + entry.getValue());
                        }

                        index++;
                    }

                    if(trains.isEmpty()){
                        System.out.println("There are no trains for this route.");
                    }else {
                        System.out.println("Select a train by typing 1,2,3..");
                        int selectedTrain = sc.nextInt();
                        trainSelectedForBooking = trains.get(selectedTrain - 1);
                    }
                    break;

                case 5:
                    if(trainSelectedForBooking == null){
                        System.out.println("Please search and select a train first.");
                        break;
                    }
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer> row: seats){
                        for(Integer val: row){
                            System.out.println(val + " ");
                        }
                        System.out.println();
                    }

                    System.out.println("Select the seat by typing the row and column");

                    System.out.println("Enter the row: ");
                    int row = sc.nextInt();

                    System.out.println("Enter column: ");
                    int col = sc.nextInt();

                    System.out.println("Enter the date of travel (YYYY-MM-DD): ");
                    String dateOfTravel = sc.next();

                    System.out.println("Booking your seat...");

                    Boolean booked = userBookingService.bookTrainSeat(
                            trainSelectedForBooking,
                            row,
                            col,
                            source,
                            dest,
                            dateOfTravel
                    );
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked!! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;

                case 6:
                    System.out.println("cancelling your booking");

                    Boolean cancelled = userBookingService.cancelBooking();

                    if(cancelled){
                        System.out.println("Booking cancelled successfully.");
                    }else{
                        System.out.println("Unable to cancel booking.");
                    }

                    break;

                default:
                    break;
            }
        }



    }
}
